name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: Create Classic Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.3 -m .pkgmeta
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    - name: Notify on Failure
      if: failure()
      env:
        BUILD_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: curl -s https://raw.githubusercontent.com/nebularg/actions-discord-webhook/master/send.sh | bash
