name: release

on: [push]
package-as: AutoLogoutAlert
enable-nolib-creation: no
ignore: # Files and directories beginning with a dot (such as .git) are automatically ignored, as is the pgkmeta file itself.

required-dependencies:

manual-changelog: CHANGELOG.txt

license-output: LICENSE.txt
